display_name: CryptoTracker

icon: linux/assets/icon.png

keywords:
  - Crypto
  - Crypto tracker
  - Crypto price

generic_name: Cryptocurrency Tracker

categories:
  - Finance

startup_notify: true

# You can specify the shared libraries that you want to bundle with your app
#
# flutter_distributor automatically detects the shared libraries that your app
# depends on, but you can also specify them manually here.

#
# The following example shows how to bundle the libcurl library with your app.
#
# include:
#   - libcurl.so.4
include: []
