display_name: CryptoTracker
package_name: cryptotracker

maintainer:
  name: judemont
  email: julien@rmbi.ch

Description:

priority: optional
section: x11
installed_size: 15700

dependencies:
  - mpv

essential: false

icon: linux/assets/icon.png

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - Crypto
  - Crypto tracker
  - Crypto price

generic_name: cryptocurrency tracker

categories:
  - Finance
startup_notify: true
